# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='signature',
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='extra_image',
            field=models.TextField(blank=True, help_text="Any arbitrary extra image that the provider would like to display on their invoice. For example, this could be the provider's signature.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='extra_image',
            field=models.ImageField(blank=True, help_text="Any arbitrary extra image that the provider would like to display on their invoice. For example, this could be the provider's signature.", null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
