# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinvoice',
            old_name='auto_pdf_on_save',
            new_name='auto_create_pdf_on_save',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='auto_pdf_on_save',
            new_name='auto_create_pdf_on_save',
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='extra_text',
            field=models.TextField(blank=True, help_text='Any arbitrary extra text that the provider would like to display on their invoice. Each template should have a designated location to place this extra text.', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='extra_text',
            field=models.TextField(blank=True, help_text='Any arbitrary extra text that the provider would like to display on their invoice. Each template should have a designated location to place this extra text.', null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='line_item_id',
            field=models.IntegerField(help_text='An ID for this line item, unique with the line item key. Can be used to store incoming ID data from 3rd parties.'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='name',
            field=models.CharField(help_text='What the item is, i.e. a formal title or summary of the item.', max_length=255),
        ),
    ]
