# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20180104_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='auto_create_pdf_on_save',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='auto_download_jira_worklogs_on_save',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='auto_upload_google_drive_on_save',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='auto_create_pdf_on_save',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='auto_download_jira_worklogs_on_save',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='auto_upload_google_drive_on_save',
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='approved',
            field=models.CharField(choices=[('automatically', 'Automatically'), ('manually', 'Manually'), ('not_approved', 'Not Approved')], default='not_approved', help_text='The approval status of this invoice.', max_length=80),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved',
            field=models.CharField(choices=[('automatically', 'Automatically'), ('manually', 'Manually'), ('not_approved', 'Not Approved')], default='not_approved', help_text='The approval status of this invoice.', max_length=80),
        ),
    ]
