# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20180116_1745'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lineitem',
            unique_together=set([('invoice', 'line_item_id', 'key')]),
        ),
    ]
