# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(help_text='The authentication user linked to this account.', on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hourlyrate',
            unique_together=set([('provider', 'client')]),
        ),
    ]
