# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180103_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyrate',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this hourly rate relationship still exists between the provider and client or not.'),
        ),
    ]
