# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20180103_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='currency',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='transferwise_recipient_id',
            field=models.IntegerField(blank=True, help_text='The TransferWise recipient ID used to identify recipient accounts which contain bank account information.', null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='identification',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'accountNumber': '', 'bic_swift': ''}, help_text='Unique identification information for this bank account.'),
        ),
    ]
