# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 11:24
from __future__ import unicode_literals

import accounting.bank.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20180104_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='identification',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=accounting.bank.models.identification_schema, help_text='Unique identification information for this bank account.'),
        ),
    ]
