# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.contrib.postgres.fields.jsonb

import accounting.bank.models


def update_identification_keys(apps, schema_editor):
    """
    Updates any identification keys for all existing bank accounts.

    Update: `accountNumber` -> `account_number`.
    Add: `currency`.
    Delete: All old keys.
    """
    BankAccount = apps.get_model('bank', 'BankAccount')
    for bank_account in BankAccount.objects.all():
        # Update: `accountNumber` -> `account_number`.
        if 'accountNumber' in bank_account.identification:
            bank_account.identification['account_number'] = bank_account.identification['accountNumber']
        # Add: `currency`.
        if 'currency' not in bank_account.identification:
            bank_account.identification['currency'] = settings.DEFAULT_CURRENCY
        # Delete: all old keys.
        for key in bank_account.identification:
            if key not in accounting.bank.models.identification_schema().keys():
                del bank_account.identification[key]
        bank_account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20180104_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='identification',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=accounting.bank.models.identification_schema, help_text='Unique identification information for this bank account.'),
        ),
        migrations.RunPython(
            update_identification_keys,
            reverse_code=lambda apps, schema_editor: None
        ),
    ]
