# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 09:35
from __future__ import unicode_literals

from django.db import migrations
import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20180104_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='identification',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'accountNumber': '', 'bic_swift': ''}, help_text='Unique identification information for this bank account.'),
        ),
    ]
