# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20180104_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='user_account',
            field=models.OneToOneField(help_text='The user account that this bank account is linked to. ', on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='account.Account'),
        ),
    ]
