# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The universally unique identifier for this model instance.', verbose_name='UUID')),
                ('country', django_countries.fields.CountryField(help_text='The country associated with this user account.', max_length=2)),
                ('address_line1', models.CharField(help_text='The first address line to appear on accounting documents, i.e. invoices.', max_length=128)),
                ('address_line2', models.CharField(blank=True, help_text='Additional line for extending an address.', max_length=128, null=True)),
                ('zipcode', models.CharField(help_text='A 5-digit or ZIP+4 zipcode. Example: 12345, 12345-6789.', max_length=10)),
                ('city', models.CharField(help_text='The city associated with this user account.', max_length=60)),
                ('state', models.CharField(blank=True, help_text='The state or province associated with this user account. Required if country is US, CA, AU, or BR.', max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
