# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(help_text='The first address line to appear on accounting documents, i.e. invoices.', max_length=128),
        ),
    ]
