# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 14:34
from __future__ import unicode_literals

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields

import accounting.common.mixins
import accounting.third_party_api.google.mixins
import accounting.transferwise.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20180103_0420'),
        ('invoice', '0005_auto_20180104_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferWiseBulkPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The universally unique identifier for this model instance.', verbose_name='UUID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date this bulk payment was created and uploaded to TransferWise. Defaults to right now, but can be changed.')),
                ('csv_path', models.URLField(blank=True, help_text='The absolute URL that can be used to retrieve the bulk payment CSV.', max_length=300, null=True)),
                ('auto_create_payments_on_save', models.BooleanField(default=False, help_text='Whether TransferWise payments should automatically be created on save. Note that currently, this does not create actual TransferWise payments through TransferWise! It only creates them internally to track different data easily.')),
                ('auto_create_csv_on_save', models.BooleanField(default=False, help_text='Whether this bulk payment should be converted into a CSV file on save.')),
                ('auto_upload_google_drive_on_save', models.BooleanField(default=False, help_text='Whether this bulk payment CSV should be uploaded to Google Drive on save.')),
                ('sender', models.ForeignKey(help_text='The sender of the TransferWise bulk payment. Refers to the account owner of the account initiating the payment.', on_delete=django.db.models.deletion.CASCADE, related_name='transferwise_sender_bulk_payments', to='account.Account')),
            ],
            options={
                'verbose_name': 'TransferWise Bulk Payment',
                'verbose_name_plural': 'TransferWise Bulk Payments',
            },
            bases=(accounting.common.mixins.ValidateModelMixin, models.Model, accounting.transferwise.mixins.TransferWiseCsvMixin, accounting.third_party_api.google.mixins.GoogleDriveMixin),
        ),
        migrations.CreateModel(
            name='TransferWisePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The universally unique identifier for this model instance.', verbose_name='UUID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date this payment was made. Defaults to right now, but can be changed.')),
                ('bulk_payment', models.ForeignKey(blank=True, help_text='The TransferWise bulk payment that this payment may be a part of.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transferwise.TransferWiseBulkPayment')),
                ('invoice', models.OneToOneField(help_text='The invoice to which this TransferWise payment belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='transferwise_payment', to='invoice.Invoice')),
            ],
            options={
                'verbose_name': 'TransferWise Payment',
                'verbose_name_plural': 'TransferWise Payments',
            },
            bases=(accounting.common.mixins.ValidateModelMixin, models.Model),
        ),
    ]
