# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone

import accounting.transferwise.models


class Migration(migrations.Migration):

    dependencies = [
        ('transferwise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferwisebulkpayment',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The end of the date interval for which to consider unpaid invoices for. Defaults to the last day of the past month.'),
        ),
        migrations.AddField(
            model_name='transferwisebulkpayment',
            name='start_date',
            field=models.DateTimeField(default=accounting.transferwise.models.ancient_date, help_text='The start of the date interval for which to consider unpaid invoices for. Defaults to an ancient date.'),
        ),
    ]
